# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad30c72dc1443da662e56422ac15d181b566f02adb2e0d3bc0259fbe4cf09b1f4a0d568044efb046ecc297497c5045c1f550bc914d8531c6f94a101b4e2263e0

test:
  secret_key_base: 4787cc25fd0d03ecaa8bef402ed6e31e85ae8578ebc9a1809665a689058bf3f9d7afecc3a1ee7a3d5015da0e020d01acc67d381cf4967d65e94d15384e290e29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
